FROM node:24.14.0-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG GITHUB_TOKEN
ARG PLAUSIBLE_DOMAIN
ARG PLAUSIBLE_ENDPOINT
RUN GITHUB_TOKEN=$GITHUB_TOKEN PLAUSIBLE_DOMAIN=$PLAUSIBLE_DOMAIN PLAUSIBLE_ENDPOINT=$PLAUSIBLE_ENDPOINT npm run build
EXPOSE 5000
CMD ["./start.sh"]
